//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationService.IICUTech")]
    public interface IICUTech
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.LoginResponse> LoginAsync(AuthenticationService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#RegisterNewCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.RegisterNewCustomerResponse> RegisterNewCustomerAsync(AuthenticationService.RegisterNewCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetCustomerInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.GetCustomerInfoResponse> GetCustomerInfoAsync(AuthenticationService.GetCustomerInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#UpdateCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.UpdateCustomerResponse> UpdateCustomerAsync(AuthenticationService.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.GetVersionResponse> GetVersionAsync(AuthenticationService.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetLocations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.GetLocationsResponse> GetLocationsAsync(AuthenticationService.GetLocationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetCameras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.GetCamerasResponse> GetCamerasAsync(AuthenticationService.GetCamerasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#SetLocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.SetLocationResponse> SetLocationAsync(AuthenticationService.SetLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#SetCamera", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.SetCameraResponse> SetCameraAsync(AuthenticationService.SetCameraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#SetAlarm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.SetAlarmResponse> SetAlarmAsync(AuthenticationService.SetAlarmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#PushRegisterDevice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.PushRegisterDeviceResponse> PushRegisterDeviceAsync(AuthenticationService.PushRegisterDeviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#PushMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.PushMessageResponse> PushMessageAsync(AuthenticationService.PushMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#SyncCameras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.SyncCamerasResponse> SyncCamerasAsync(AuthenticationService.SyncCamerasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetNotifications", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.GetNotificationsResponse> GetNotificationsAsync(AuthenticationService.GetNotificationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetNotificationsCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.GetNotificationsCountResponse> GetNotificationsCountAsync(AuthenticationService.GetNotificationsCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#AddClip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.AddClipResponse> AddClipAsync(AuthenticationService.AddClipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetClips", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.GetClipsResponse> GetClipsAsync(AuthenticationService.GetClipsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetClipsCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.GetClipsCountResponse> GetClipsCountAsync(AuthenticationService.GetClipsCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#DeleteNotification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.DeleteNotificationResponse> DeleteNotificationAsync(AuthenticationService.DeleteNotificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#Encrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.EncryptResponse> EncryptAsync(AuthenticationService.EncryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#Crypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<AuthenticationService.CryptResponse> CryptAsync(AuthenticationService.CryptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string IPs;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(string UserName, string Password, string IPs)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.IPs = IPs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class LoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public LoginResponse()
        {
        }
        
        public LoginResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterNewCustomer", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class RegisterNewCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string LastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int CountryID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int aID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string SignupIP;
        
        public RegisterNewCustomerRequest()
        {
        }
        
        public RegisterNewCustomerRequest(string Email, string Password, string FirstName, string LastName, string Mobile, int CountryID, int aID, string SignupIP)
        {
            this.Email = Email;
            this.Password = Password;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Mobile = Mobile;
            this.CountryID = CountryID;
            this.aID = aID;
            this.SignupIP = SignupIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterNewCustomerResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class RegisterNewCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public RegisterNewCustomerResponse()
        {
        }
        
        public RegisterNewCustomerResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerInfo", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetCustomerInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        public GetCustomerInfoRequest()
        {
        }
        
        public GetCustomerInfoRequest(int EntityID, string Username, string Password)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerInfoResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetCustomerInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetCustomerInfoResponse()
        {
        }
        
        public GetCustomerInfoResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomer", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class UpdateCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ValuesArray;
        
        public UpdateCustomerRequest()
        {
        }
        
        public UpdateCustomerRequest(int EntityID, string Username, string Password, string ValuesArray)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.ValuesArray = ValuesArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomerResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class UpdateCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public UpdateCustomerResponse()
        {
        }
        
        public UpdateCustomerResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersion", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetVersionRequest
    {
        
        public GetVersionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersionResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetVersionResponse()
        {
        }
        
        public GetVersionResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLocations", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetLocationsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        public GetLocationsRequest()
        {
        }
        
        public GetLocationsRequest(int EntityID, string Username, string Password)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLocationsResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetLocationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetLocationsResponse()
        {
        }
        
        public GetLocationsResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCameras", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetCamerasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        public GetCamerasRequest()
        {
        }
        
        public GetCamerasRequest(int EntityID, string Username, string Password)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCamerasResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetCamerasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetCamerasResponse()
        {
        }
        
        public GetCamerasResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetLocation", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetLocationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string IP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int Port;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int MediaPort;
        
        public SetLocationRequest()
        {
        }
        
        public SetLocationRequest(int EntityID, string Username, string Password, string IP, int Port, int MediaPort)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.IP = IP;
            this.Port = Port;
            this.MediaPort = MediaPort;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetLocationResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetLocationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SetLocationResponse()
        {
        }
        
        public SetLocationResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCamera", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetCameraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string LocationName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string URL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int CameraId;
        
        public SetCameraRequest()
        {
        }
        
        public SetCameraRequest(int EntityID, string Username, string Password, string LocationName, string URL, int CameraId)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.LocationName = LocationName;
            this.URL = URL;
            this.CameraId = CameraId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCameraResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetCameraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SetCameraResponse()
        {
        }
        
        public SetCameraResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetAlarm", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetAlarmRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int Status;
        
        public SetAlarmRequest()
        {
        }
        
        public SetAlarmRequest(int EntityID, string Username, string Password, int Status)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetAlarmResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetAlarmResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SetAlarmResponse()
        {
        }
        
        public SetAlarmResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushRegisterDevice", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class PushRegisterDeviceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string UDID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string DeviceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int TypeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public bool AllowNotification;
        
        public PushRegisterDeviceRequest()
        {
        }
        
        public PushRegisterDeviceRequest(int EntityID, string Username, string Password, string UDID, string DeviceID, int TypeId, bool AllowNotification)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.UDID = UDID;
            this.DeviceID = DeviceID;
            this.TypeId = TypeId;
            this.AllowNotification = AllowNotification;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushRegisterDeviceResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class PushRegisterDeviceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public PushRegisterDeviceResponse()
        {
        }
        
        public PushRegisterDeviceResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushMessage", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class PushMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string FunctionPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int KindType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int KindID;
        
        public PushMessageRequest()
        {
        }
        
        public PushMessageRequest(int EntityID, string Username, string Password, string text, string FunctionPassword, int KindType, int KindID)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.text = text;
            this.FunctionPassword = FunctionPassword;
            this.KindType = KindType;
            this.KindID = KindID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushMessageResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class PushMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public PushMessageResponse()
        {
        }
        
        public PushMessageResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncCameras", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SyncCamerasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int CamerasCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int[] CameraIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string[] CameraNames;
        
        public SyncCamerasRequest()
        {
        }
        
        public SyncCamerasRequest(int EntityID, string Username, string Password, int CamerasCount, int[] CameraIds, string[] CameraNames)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.CamerasCount = CamerasCount;
            this.CameraIds = CameraIds;
            this.CameraNames = CameraNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncCamerasResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SyncCamerasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SyncCamerasResponse()
        {
        }
        
        public SyncCamerasResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotifications", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetNotificationsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string UDID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int LimitTo;
        
        public GetNotificationsRequest()
        {
        }
        
        public GetNotificationsRequest(int EntityID, string Username, string Password, string UDID, int ResultType, int LimitFrom, int LimitTo)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.UDID = UDID;
            this.ResultType = ResultType;
            this.LimitFrom = LimitFrom;
            this.LimitTo = LimitTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotificationsResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetNotificationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetNotificationsResponse()
        {
        }
        
        public GetNotificationsResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotificationsCount", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetNotificationsCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string UDID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int ResultType;
        
        public GetNotificationsCountRequest()
        {
        }
        
        public GetNotificationsCountRequest(int EntityID, string Username, string Password, string UDID, int ResultType)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.UDID = UDID;
            this.ResultType = ResultType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotificationsCountResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetNotificationsCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetNotificationsCountResponse()
        {
        }
        
        public GetNotificationsCountResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddClip", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class AddClipRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int cameraID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int clipID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int ClipLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string ClipDate;
        
        public AddClipRequest()
        {
        }
        
        public AddClipRequest(int EntityId, string UserName, string Password, int cameraID, int clipID, int ClipLength, string ClipDate)
        {
            this.EntityId = EntityId;
            this.UserName = UserName;
            this.Password = Password;
            this.cameraID = cameraID;
            this.clipID = clipID;
            this.ClipLength = ClipLength;
            this.ClipDate = ClipDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddClipResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class AddClipResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AddClipResponse()
        {
        }
        
        public AddClipResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClips", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetClipsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int cameraID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string DateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string DateTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int LimitTo;
        
        public GetClipsRequest()
        {
        }
        
        public GetClipsRequest(int EntityId, string UserName, string Password, int ResultType, int cameraID, string DateFrom, string DateTo, int LimitFrom, int LimitTo)
        {
            this.EntityId = EntityId;
            this.UserName = UserName;
            this.Password = Password;
            this.ResultType = ResultType;
            this.cameraID = cameraID;
            this.DateFrom = DateFrom;
            this.DateTo = DateTo;
            this.LimitFrom = LimitFrom;
            this.LimitTo = LimitTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClipsResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetClipsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetClipsResponse()
        {
        }
        
        public GetClipsResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClipsCount", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetClipsCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int cameraID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string DateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string DateTo;
        
        public GetClipsCountRequest()
        {
        }
        
        public GetClipsCountRequest(int EntityId, string UserName, string Password, int ResultType, int cameraID, string DateFrom, string DateTo)
        {
            this.EntityId = EntityId;
            this.UserName = UserName;
            this.Password = Password;
            this.ResultType = ResultType;
            this.cameraID = cameraID;
            this.DateFrom = DateFrom;
            this.DateTo = DateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClipsCountResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetClipsCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetClipsCountResponse()
        {
        }
        
        public GetClipsCountResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteNotification", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class DeleteNotificationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int NotificationID;
        
        public DeleteNotificationRequest()
        {
        }
        
        public DeleteNotificationRequest(int EntityID, string Username, string Password, int NotificationID)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.NotificationID = NotificationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteNotificationResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class DeleteNotificationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public DeleteNotificationResponse()
        {
        }
        
        public DeleteNotificationResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Encrypt", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class EncryptRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string DataString;
        
        public EncryptRequest()
        {
        }
        
        public EncryptRequest(string DataString)
        {
            this.DataString = DataString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class EncryptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public EncryptResponse()
        {
        }
        
        public EncryptResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crypt", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class CryptRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string FuncPassword;
        
        public CryptRequest()
        {
        }
        
        public CryptRequest(int EntityId, string UserName, string Password, string FuncPassword)
        {
            this.EntityId = EntityId;
            this.UserName = UserName;
            this.Password = Password;
            this.FuncPassword = FuncPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CryptResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class CryptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public CryptResponse()
        {
        }
        
        public CryptResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IICUTechChannel : AuthenticationService.IICUTech, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ICUTechClient : System.ServiceModel.ClientBase<AuthenticationService.IICUTech>, AuthenticationService.IICUTech
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ICUTechClient() : 
                base(ICUTechClient.GetDefaultBinding(), ICUTechClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IICUTechPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ICUTechClient(EndpointConfiguration endpointConfiguration) : 
                base(ICUTechClient.GetBindingForEndpoint(endpointConfiguration), ICUTechClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ICUTechClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ICUTechClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ICUTechClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ICUTechClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ICUTechClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.LoginResponse> AuthenticationService.IICUTech.LoginAsync(AuthenticationService.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.LoginResponse> LoginAsync(string UserName, string Password, string IPs)
        {
            AuthenticationService.LoginRequest inValue = new AuthenticationService.LoginRequest();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.IPs = IPs;
            return ((AuthenticationService.IICUTech)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.RegisterNewCustomerResponse> AuthenticationService.IICUTech.RegisterNewCustomerAsync(AuthenticationService.RegisterNewCustomerRequest request)
        {
            return base.Channel.RegisterNewCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.RegisterNewCustomerResponse> RegisterNewCustomerAsync(string Email, string Password, string FirstName, string LastName, string Mobile, int CountryID, int aID, string SignupIP)
        {
            AuthenticationService.RegisterNewCustomerRequest inValue = new AuthenticationService.RegisterNewCustomerRequest();
            inValue.Email = Email;
            inValue.Password = Password;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Mobile = Mobile;
            inValue.CountryID = CountryID;
            inValue.aID = aID;
            inValue.SignupIP = SignupIP;
            return ((AuthenticationService.IICUTech)(this)).RegisterNewCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.GetCustomerInfoResponse> AuthenticationService.IICUTech.GetCustomerInfoAsync(AuthenticationService.GetCustomerInfoRequest request)
        {
            return base.Channel.GetCustomerInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.GetCustomerInfoResponse> GetCustomerInfoAsync(int EntityID, string Username, string Password)
        {
            AuthenticationService.GetCustomerInfoRequest inValue = new AuthenticationService.GetCustomerInfoRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            return ((AuthenticationService.IICUTech)(this)).GetCustomerInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.UpdateCustomerResponse> AuthenticationService.IICUTech.UpdateCustomerAsync(AuthenticationService.UpdateCustomerRequest request)
        {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.UpdateCustomerResponse> UpdateCustomerAsync(int EntityID, string Username, string Password, string ValuesArray)
        {
            AuthenticationService.UpdateCustomerRequest inValue = new AuthenticationService.UpdateCustomerRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.ValuesArray = ValuesArray;
            return ((AuthenticationService.IICUTech)(this)).UpdateCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.GetVersionResponse> AuthenticationService.IICUTech.GetVersionAsync(AuthenticationService.GetVersionRequest request)
        {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.GetVersionResponse> GetVersionAsync()
        {
            AuthenticationService.GetVersionRequest inValue = new AuthenticationService.GetVersionRequest();
            return ((AuthenticationService.IICUTech)(this)).GetVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.GetLocationsResponse> AuthenticationService.IICUTech.GetLocationsAsync(AuthenticationService.GetLocationsRequest request)
        {
            return base.Channel.GetLocationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.GetLocationsResponse> GetLocationsAsync(int EntityID, string Username, string Password)
        {
            AuthenticationService.GetLocationsRequest inValue = new AuthenticationService.GetLocationsRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            return ((AuthenticationService.IICUTech)(this)).GetLocationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.GetCamerasResponse> AuthenticationService.IICUTech.GetCamerasAsync(AuthenticationService.GetCamerasRequest request)
        {
            return base.Channel.GetCamerasAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.GetCamerasResponse> GetCamerasAsync(int EntityID, string Username, string Password)
        {
            AuthenticationService.GetCamerasRequest inValue = new AuthenticationService.GetCamerasRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            return ((AuthenticationService.IICUTech)(this)).GetCamerasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.SetLocationResponse> AuthenticationService.IICUTech.SetLocationAsync(AuthenticationService.SetLocationRequest request)
        {
            return base.Channel.SetLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.SetLocationResponse> SetLocationAsync(int EntityID, string Username, string Password, string IP, int Port, int MediaPort)
        {
            AuthenticationService.SetLocationRequest inValue = new AuthenticationService.SetLocationRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.IP = IP;
            inValue.Port = Port;
            inValue.MediaPort = MediaPort;
            return ((AuthenticationService.IICUTech)(this)).SetLocationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.SetCameraResponse> AuthenticationService.IICUTech.SetCameraAsync(AuthenticationService.SetCameraRequest request)
        {
            return base.Channel.SetCameraAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.SetCameraResponse> SetCameraAsync(int EntityID, string Username, string Password, string LocationName, string URL, int CameraId)
        {
            AuthenticationService.SetCameraRequest inValue = new AuthenticationService.SetCameraRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.LocationName = LocationName;
            inValue.URL = URL;
            inValue.CameraId = CameraId;
            return ((AuthenticationService.IICUTech)(this)).SetCameraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.SetAlarmResponse> AuthenticationService.IICUTech.SetAlarmAsync(AuthenticationService.SetAlarmRequest request)
        {
            return base.Channel.SetAlarmAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.SetAlarmResponse> SetAlarmAsync(int EntityID, string Username, string Password, int Status)
        {
            AuthenticationService.SetAlarmRequest inValue = new AuthenticationService.SetAlarmRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Status = Status;
            return ((AuthenticationService.IICUTech)(this)).SetAlarmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.PushRegisterDeviceResponse> AuthenticationService.IICUTech.PushRegisterDeviceAsync(AuthenticationService.PushRegisterDeviceRequest request)
        {
            return base.Channel.PushRegisterDeviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.PushRegisterDeviceResponse> PushRegisterDeviceAsync(int EntityID, string Username, string Password, string UDID, string DeviceID, int TypeId, bool AllowNotification)
        {
            AuthenticationService.PushRegisterDeviceRequest inValue = new AuthenticationService.PushRegisterDeviceRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.UDID = UDID;
            inValue.DeviceID = DeviceID;
            inValue.TypeId = TypeId;
            inValue.AllowNotification = AllowNotification;
            return ((AuthenticationService.IICUTech)(this)).PushRegisterDeviceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.PushMessageResponse> AuthenticationService.IICUTech.PushMessageAsync(AuthenticationService.PushMessageRequest request)
        {
            return base.Channel.PushMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.PushMessageResponse> PushMessageAsync(int EntityID, string Username, string Password, string text, string FunctionPassword, int KindType, int KindID)
        {
            AuthenticationService.PushMessageRequest inValue = new AuthenticationService.PushMessageRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.text = text;
            inValue.FunctionPassword = FunctionPassword;
            inValue.KindType = KindType;
            inValue.KindID = KindID;
            return ((AuthenticationService.IICUTech)(this)).PushMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.SyncCamerasResponse> AuthenticationService.IICUTech.SyncCamerasAsync(AuthenticationService.SyncCamerasRequest request)
        {
            return base.Channel.SyncCamerasAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.SyncCamerasResponse> SyncCamerasAsync(int EntityID, string Username, string Password, int CamerasCount, int[] CameraIds, string[] CameraNames)
        {
            AuthenticationService.SyncCamerasRequest inValue = new AuthenticationService.SyncCamerasRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.CamerasCount = CamerasCount;
            inValue.CameraIds = CameraIds;
            inValue.CameraNames = CameraNames;
            return ((AuthenticationService.IICUTech)(this)).SyncCamerasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.GetNotificationsResponse> AuthenticationService.IICUTech.GetNotificationsAsync(AuthenticationService.GetNotificationsRequest request)
        {
            return base.Channel.GetNotificationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.GetNotificationsResponse> GetNotificationsAsync(int EntityID, string Username, string Password, string UDID, int ResultType, int LimitFrom, int LimitTo)
        {
            AuthenticationService.GetNotificationsRequest inValue = new AuthenticationService.GetNotificationsRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.UDID = UDID;
            inValue.ResultType = ResultType;
            inValue.LimitFrom = LimitFrom;
            inValue.LimitTo = LimitTo;
            return ((AuthenticationService.IICUTech)(this)).GetNotificationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.GetNotificationsCountResponse> AuthenticationService.IICUTech.GetNotificationsCountAsync(AuthenticationService.GetNotificationsCountRequest request)
        {
            return base.Channel.GetNotificationsCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.GetNotificationsCountResponse> GetNotificationsCountAsync(int EntityID, string Username, string Password, string UDID, int ResultType)
        {
            AuthenticationService.GetNotificationsCountRequest inValue = new AuthenticationService.GetNotificationsCountRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.UDID = UDID;
            inValue.ResultType = ResultType;
            return ((AuthenticationService.IICUTech)(this)).GetNotificationsCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.AddClipResponse> AuthenticationService.IICUTech.AddClipAsync(AuthenticationService.AddClipRequest request)
        {
            return base.Channel.AddClipAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.AddClipResponse> AddClipAsync(int EntityId, string UserName, string Password, int cameraID, int clipID, int ClipLength, string ClipDate)
        {
            AuthenticationService.AddClipRequest inValue = new AuthenticationService.AddClipRequest();
            inValue.EntityId = EntityId;
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.cameraID = cameraID;
            inValue.clipID = clipID;
            inValue.ClipLength = ClipLength;
            inValue.ClipDate = ClipDate;
            return ((AuthenticationService.IICUTech)(this)).AddClipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.GetClipsResponse> AuthenticationService.IICUTech.GetClipsAsync(AuthenticationService.GetClipsRequest request)
        {
            return base.Channel.GetClipsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.GetClipsResponse> GetClipsAsync(int EntityId, string UserName, string Password, int ResultType, int cameraID, string DateFrom, string DateTo, int LimitFrom, int LimitTo)
        {
            AuthenticationService.GetClipsRequest inValue = new AuthenticationService.GetClipsRequest();
            inValue.EntityId = EntityId;
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.ResultType = ResultType;
            inValue.cameraID = cameraID;
            inValue.DateFrom = DateFrom;
            inValue.DateTo = DateTo;
            inValue.LimitFrom = LimitFrom;
            inValue.LimitTo = LimitTo;
            return ((AuthenticationService.IICUTech)(this)).GetClipsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.GetClipsCountResponse> AuthenticationService.IICUTech.GetClipsCountAsync(AuthenticationService.GetClipsCountRequest request)
        {
            return base.Channel.GetClipsCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.GetClipsCountResponse> GetClipsCountAsync(int EntityId, string UserName, string Password, int ResultType, int cameraID, string DateFrom, string DateTo)
        {
            AuthenticationService.GetClipsCountRequest inValue = new AuthenticationService.GetClipsCountRequest();
            inValue.EntityId = EntityId;
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.ResultType = ResultType;
            inValue.cameraID = cameraID;
            inValue.DateFrom = DateFrom;
            inValue.DateTo = DateTo;
            return ((AuthenticationService.IICUTech)(this)).GetClipsCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.DeleteNotificationResponse> AuthenticationService.IICUTech.DeleteNotificationAsync(AuthenticationService.DeleteNotificationRequest request)
        {
            return base.Channel.DeleteNotificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.DeleteNotificationResponse> DeleteNotificationAsync(int EntityID, string Username, string Password, int NotificationID)
        {
            AuthenticationService.DeleteNotificationRequest inValue = new AuthenticationService.DeleteNotificationRequest();
            inValue.EntityID = EntityID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.NotificationID = NotificationID;
            return ((AuthenticationService.IICUTech)(this)).DeleteNotificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.EncryptResponse> AuthenticationService.IICUTech.EncryptAsync(AuthenticationService.EncryptRequest request)
        {
            return base.Channel.EncryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.EncryptResponse> EncryptAsync(string DataString)
        {
            AuthenticationService.EncryptRequest inValue = new AuthenticationService.EncryptRequest();
            inValue.DataString = DataString;
            return ((AuthenticationService.IICUTech)(this)).EncryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationService.CryptResponse> AuthenticationService.IICUTech.CryptAsync(AuthenticationService.CryptRequest request)
        {
            return base.Channel.CryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.CryptResponse> CryptAsync(int EntityId, string UserName, string Password, string FuncPassword)
        {
            AuthenticationService.CryptRequest inValue = new AuthenticationService.CryptRequest();
            inValue.EntityId = EntityId;
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.FuncPassword = FuncPassword;
            return ((AuthenticationService.IICUTech)(this)).CryptAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IICUTechPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IICUTechPort))
            {
                return new System.ServiceModel.EndpointAddress("http://isapi.icu-tech.com/icutech-test.dll/soap/IICUTech");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ICUTechClient.GetBindingForEndpoint(EndpointConfiguration.IICUTechPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ICUTechClient.GetEndpointAddress(EndpointConfiguration.IICUTechPort);
        }
        
        public enum EndpointConfiguration
        {
            
            IICUTechPort,
        }
    }
}
